/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depucount.main.interfaces;

import com.depucount.main.utils.DatabaseTools;
import com.depucount.main.models.BasicWorkEntry;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vilmars.vesingi
 */
public class AddNewCategory extends javax.swing.JDialog {

    /**
     * Creates new form AddNewCategory
     */
    public AddNewCategory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categoryAddingBtn = new javax.swing.JButton();
        categoryNameToBeAdded = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kategorija");

        categoryAddingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new task.png"))); // NOI18N
        categoryAddingBtn.setText("Pievienot");
        categoryAddingBtn.setIconTextGap(10);
        categoryAddingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAddingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryNameToBeAdded)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addComponent(categoryAddingBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryNameToBeAdded)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryAddingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryAddingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAddingBtnActionPerformed

        Boolean categoryPresent = false;
        if (categoryNameToBeAdded.getText().length() > 4) {

            ArrayList<BasicWorkEntry> listToCheck = MainInterface.getCurrentListInProgess();
            if (listToCheck != null) {
                for (BasicWorkEntry entry : listToCheck) {

                    if (categoryNameToBeAdded.equals(entry.getWorkName())) {
                        categoryPresent = true;
                        break;
                    }
                }
            }
            if (!categoryPresent) {
                DatabaseTools.setPossibleNewCategory(categoryNameToBeAdded.getText());
                JOptionPane.showMessageDialog(this, "Kategorija pievienota");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Šāda kategorija jau ir pievienota");

            }
        } else {
            JOptionPane.showMessageDialog(this, "Kategorija ir par īsu");
        }
    }//GEN-LAST:event_categoryAddingBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewCategory dialog = new AddNewCategory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryAddingBtn;
    private javax.swing.JTextField categoryNameToBeAdded;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
