/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depucount.main.interfaces;

import com.depucount.main.DatabaseProcessor;

import com.depucount.main.utils.DatabaseTools;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author vilmars.vesingi
 */
public class AddNewDBlink extends javax.swing.JDialog {

    public static String newDBlocation;

    public static String getNewDBlocation() {
        return newDBlocation;
    }

    public static void setNewDBlocation(String newDBlocation) {
        AddNewDBlink.newDBlocation = newDBlocation;
    }

    /**
     * Creates new form AddNewDBlink
     */
    public AddNewDBlink(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newDBdirectoryChooser = new javax.swing.JFileChooser();
        newDBDirectoryFinder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newDBtitle = new javax.swing.JTextField();
        newDBcreateBtn = new javax.swing.JButton();
        newDBlocationLabel = new javax.swing.JLabel();

        newDBdirectoryChooser.setCurrentDirectory(new java.io.File("C:\\visma\\xml"));
        newDBdirectoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        newDBDirectoryFinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        newDBDirectoryFinder.setText("Atvērt...");
        newDBDirectoryFinder.setIconTextGap(10);
        newDBDirectoryFinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDBDirectoryFinderActionPerformed(evt);
            }
        });

        jLabel1.setText("Veidot jaunu datubāzi");

        jLabel2.setText("Nosaukums");

        jLabel3.setText("Saglabāt...");

        newDBcreateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new db.png"))); // NOI18N
        newDBcreateBtn.setText("Izveidot");
        newDBcreateBtn.setIconTextGap(10);
        newDBcreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDBcreateBtnActionPerformed(evt);
            }
        });

        newDBlocationLabel.setText("Nav norādīta vieta...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newDBcreateBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newDBtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newDBDirectoryFinder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newDBlocationLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newDBtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newDBDirectoryFinder)
                    .addComponent(newDBlocationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDBcreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDBDirectoryFinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDBDirectoryFinderActionPerformed

        int newDBdirChosen = newDBdirectoryChooser.showOpenDialog(null);
        if (newDBdirChosen == JFileChooser.APPROVE_OPTION) {
            setNewDBlocation(newDBdirectoryChooser.getSelectedFile().getAbsolutePath());
            newDBlocationLabel.setText(getNewDBlocation().substring(1, 15));

        }

    }//GEN-LAST:event_newDBDirectoryFinderActionPerformed

    private void newDBcreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDBcreateBtnActionPerformed

        File directory = new File(getNewDBlocation());

        if (directory.exists()
                && directory.isDirectory()) {
            if (newDBtitle.getText().length() > 1) {

                DatabaseProcessor.setNewDBAdded(true);
                DatabaseProcessor.setFileNameDB(newDBtitle.getText() + ".xml");
                DatabaseProcessor.setFilepathDB(getNewDBlocation() + "\\" + DatabaseProcessor.getFileNameDB());

                JOptionPane.showMessageDialog(this, "Jauna datubāze satavota");
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Nosaukumam vajadzētu sastāvēt vismaz no 1 simbola");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izvēlies pareizu datubāzes saglabāšanas vietu");
        }

    }//GEN-LAST:event_newDBcreateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewDBlink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewDBlink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewDBlink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewDBlink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewDBlink dialog = new AddNewDBlink(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton newDBDirectoryFinder;
    private javax.swing.JButton newDBcreateBtn;
    private javax.swing.JFileChooser newDBdirectoryChooser;
    private javax.swing.JLabel newDBlocationLabel;
    private javax.swing.JTextField newDBtitle;
    // End of variables declaration//GEN-END:variables
}
