/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.depucount.main.interfaces;

import com.depucount.main.DatabaseProcessor;

import com.depucount.main.utils.DatabaseTools;
import com.depucount.main.utils.OverviewTools;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author vilmars.vesingi
 */
public class OverviewDoc extends javax.swing.JDialog {

    /**
     * Creates new form AddNewDBlink
     */
    public OverviewDoc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newOverviewSaveLocation = new javax.swing.JFileChooser();
        newOverviewDocDirectoryFinder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newOverviewDoctitle = new javax.swing.JTextField();
        newOverviewDoccreateBtn = new javax.swing.JButton();
        newDocLabel = new javax.swing.JLabel();

        newOverviewSaveLocation.setCurrentDirectory(new java.io.File("C:\\visma\\xml"));
        newOverviewSaveLocation.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        newOverviewDocDirectoryFinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        newOverviewDocDirectoryFinder.setText("Atvērt...");
        newOverviewDocDirectoryFinder.setIconTextGap(10);
        newOverviewDocDirectoryFinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOverviewDocDirectoryFinderActionPerformed(evt);
            }
        });

        jLabel1.setText("Saglabāt pārskatu kā .doc");

        jLabel2.setText("Nosaukums");

        jLabel3.setText("Saglabāt...");

        newOverviewDoccreateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new db.png"))); // NOI18N
        newOverviewDoccreateBtn.setText("Izveidot");
        newOverviewDoccreateBtn.setIconTextGap(10);
        newOverviewDoccreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOverviewDoccreateBtnActionPerformed(evt);
            }
        });

        newDocLabel.setText("Nav norādīta vieta...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newOverviewDoccreateBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newOverviewDoctitle, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(newOverviewDocDirectoryFinder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(newDocLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newOverviewDoctitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newOverviewDocDirectoryFinder)
                    .addComponent(newDocLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newOverviewDoccreateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newOverviewDocDirectoryFinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOverviewDocDirectoryFinderActionPerformed

        int newDBdirChosen = newOverviewSaveLocation.showOpenDialog(null);
        if (newDBdirChosen == JFileChooser.APPROVE_OPTION) {
            OverviewTools.setOverviewDocLocation(newOverviewSaveLocation.getSelectedFile().getAbsolutePath());
            newDocLabel.setText(OverviewTools.getOverviewDocLocation().substring(1, 15));
        }

    }//GEN-LAST:event_newOverviewDocDirectoryFinderActionPerformed

    private void newOverviewDoccreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOverviewDoccreateBtnActionPerformed

        File directory = new File(OverviewTools.getOverviewDocLocation());
        String docName = newOverviewDoctitle.getText();
        

        if (directory.exists() && directory.isDirectory()) {
            if (docName.length() > 1) {
                OverviewTools.setOverviewDocFullPathName(OverviewTools.getOverviewDocLocation() + "\\" + docName + ".doc");
                OverviewTools.CreateOverviewDoc();
                JOptionPane.showMessageDialog(this, "Jauns dokuments satavots");
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Nosaukumam vajadzētu sastāvēt vismaz no 1 simbola");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Izvēlies pareizu dokumenta saglabāšanas vietu");
        }

    }//GEN-LAST:event_newOverviewDoccreateBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverviewDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverviewDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverviewDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverviewDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OverviewDoc dialog = new OverviewDoc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel newDocLabel;
    private javax.swing.JButton newOverviewDocDirectoryFinder;
    private javax.swing.JButton newOverviewDoccreateBtn;
    private javax.swing.JTextField newOverviewDoctitle;
    private javax.swing.JFileChooser newOverviewSaveLocation;
    // End of variables declaration//GEN-END:variables
}
